#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# security_signout:
#   path: /logout
# signup:
#   path: /api/security/signup
#   controller: App\Controller\SecurityController::signUp
#   methods: POST
api_login_check:
  path: /api/login_check
